### forge Rings
POST http://localhost:8080/rings

### get all Rings
GET http://localhost:8080/rings

### craft Silmarilli
POST http://localhost:8080/silmarilli

### get all Silmarilli
GET http://localhost:8080/silmarilli


